apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deploy
  namespace: delta-ev-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ev-pricing
  template:
    metadata:
      labels:
        app: ev-pricing
    spec:
      containers:
      - name: api
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting Pricing Engine..."
            while true; do echo -e "HTTP/1.1 200 OK\n\n{\"base_price\": 100}" | nc -l -p 8000; done
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ev-pricing
  namespace: delta-ev-platform
spec:
  type: ClusterIP
  selector:
    app: ev-pricing
  ports:
    - port: 80
      targetPort: 8000
